version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moneyflows_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.e2e
      target: deps
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/moneyflows_test
    volumes:
      - ../db:/app/db
      - ../drizzle.config.ts:/app/drizzle.config.ts
    command: bun run db:migrate
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.e2e
      target: production
    ports:
      - "3000:3000"
    env_file:
      - ../.env.e2e
    depends_on:
      migrate:
        condition: service_completed_successfully
