import { Transaction } from "./types";

export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    type: "income",
    amount: 280000,
    description: "1月給与",
    date: "2024-01-25",
    category: "給与",
    tags: ["定期収入", "メイン収入"],
  },
  {
    id: "t2",
    type: "expense",
    amount: 85000,
    description: "1月家賃",
    date: "2024-01-25",
    category: "住居費",
    tags: ["固定費"],
  },
  {
    id: "t3",
    type: "expense",
    amount: 12000,
    description: "電気代",
    date: "2024-01-24",
    category: "光熱費",
    tags: ["固定費"],
  },
  {
    id: "t4",
    type: "expense",
    amount: 8500,
    description: "ガス代",
    date: "2024-01-24",
    category: "光熱費",
    tags: ["固定費"],
  },
  {
    id: "t5",
    type: "expense",
    amount: 4500,
    description: "水道代",
    date: "2024-01-24",
    category: "光熱費",
    tags: ["固定費"],
  },
  {
    id: "t6",
    type: "expense",
    amount: 5200,
    description: "携帯電話代",
    date: "2024-01-23",
    category: "通信費",
    tags: ["固定費"],
  },
  {
    id: "t7",
    type: "expense",
    amount: 4800,
    description: "インターネット",
    date: "2024-01-23",
    category: "通信費",
    tags: ["固定費"],
  },
  {
    id: "t8",
    type: "expense",
    amount: 12000,
    description: "食材（スーパー）",
    date: "2024-01-22",
    category: "食費",
    tags: [],
  },
  {
    id: "t9",
    type: "expense",
    amount: 3500,
    description: "ランチ",
    date: "2024-01-22",
    category: "食費",
    tags: ["外食"],
  },
  {
    id: "t10",
    type: "expense",
    amount: 15000,
    description: "服",
    date: "2024-01-21",
    category: "衣服",
    tags: ["買い物"],
  },
  {
    id: "t11",
    type: "income",
    amount: 50000,
    description: "副業収入",
    date: "2024-01-20",
    category: "その他収入",
    tags: ["副業"],
  },
  {
    id: "t12",
    type: "expense",
    amount: 2500,
    description: "映画",
    date: "2024-01-20",
    category: "娯楽",
    tags: ["趣味"],
  },
  {
    id: "t13",
    type: "expense",
    amount: 4500,
    description: "本",
    date: "2024-01-19",
    category: "娯楽",
    tags: ["趣味"],
  },
  {
    id: "t14",
    type: "expense",
    amount: 3000,
    description: "ジム会費",
    date: "2024-01-19",
    category: "健康",
    tags: ["固定費"],
  },
  {
    id: "t15",
    type: "expense",
    amount: 8000,
    description: "美容院",
    date: "2024-01-18",
    category: "美容",
    tags: ["生活費", "月次", "自己投資"],
  },
  {
    id: "t16",
    type: "expense",
    amount: 6500,
    description: "飲み会",
    date: "2024-01-18",
    category: "交際費",
    tags: ["外食"],
  },
  {
    id: "t17",
    type: "expense",
    amount: 2800,
    description: "文房具",
    date: "2024-01-17",
    category: "日用品",
    tags: ["仕事"],
  },
  {
    id: "t18",
    type: "expense",
    amount: 1500,
    description: "コーヒー",
    date: "2024-01-17",
    category: "食費",
    tags: ["カフェ"],
  },
  {
    id: "t19",
    type: "expense",
    amount: 35000,
    description: "英会話スクール",
    date: "2024-01-16",
    category: "教育",
    tags: ["自己投資"],
  },
  {
    id: "t20",
    type: "income",
    amount: 30000,
    description: "株式配当",
    date: "2024-01-16",
    category: "投資収入",
    tags: ["配当"],
  },
  {
    id: "t21",
    type: "expense",
    amount: 4200,
    description: "ヘアケア用品",
    date: "2024-01-15",
    category: "美容",
    tags: ["日用品"],
  },
  {
    id: "t22",
    type: "expense",
    amount: 7500,
    description: "友人への誕生日プレゼント",
    date: "2024-01-15",
    category: "交際費",
    tags: ["プレゼント"],
  },
  {
    id: "t23",
    type: "expense",
    amount: 9800,
    description: "サプリメント",
    date: "2024-01-14",
    category: "健康",
    tags: ["日用品"],
  },
  {
    id: "t24",
    type: "expense",
    amount: 2000,
    description: "駐輪場代",
    date: "2024-01-14",
    category: "交通費",
    tags: ["固定費"],
  },
  {
    id: "t25",
    type: "expense",
    amount: 4500,
    description: "映画とポップコーン",
    date: "2024-01-13",
    category: "娯楽",
    tags: ["趣味"],
  },
  {
    id: "t26",
    type: "expense",
    amount: 13000,
    description: "靴",
    date: "2024-01-13",
    category: "衣服",
    tags: ["買い物"],
  },
  {
    id: "t27",
    type: "income",
    amount: 10000,
    description: "フリマアプリ売上",
    date: "2024-01-12",
    category: "その他収入",
    tags: ["副業"],
  },
  {
    id: "t28",
    type: "expense",
    amount: 5600,
    description: "洗剤・掃除用品",
    date: "2024-01-12",
    category: "日用品",
    tags: ["生活費"],
  },
  {
    id: "t29",
    type: "expense",
    amount: 3200,
    description: "ペット用品",
    date: "2024-01-11",
    category: "ペット",
    tags: ["生活費"],
  },
  {
    id: "t30",
    type: "expense",
    amount: 4800,
    description: "音楽サブスク年間契約",
    date: "2024-01-11",
    category: "娯楽",
    tags: ["固定費", "サブスク", "年間契約", "趣味"],
  },
];
